/*
 * This source file was generated by the Gradle 'init' task
 */
package color.calculator;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CalculatorTest {
    @Test void appHasAGreeting() {
        Calculator classUnderTest = new Calculator();
    }
}
